# Generated by Django 3.2.8 on 2021-11-01 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_registeruser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registeruser',
            options={'managed': True},
        ),
    ]
